name: Deploy Backend AI Microservice

on:
  push:
    branches: [main]
    paths:
      - "AI/**"
      - ".github/workflows/back_deploy.yml"
  pull_request:
    branches: [main]
    paths:
      - "AI/**"
      - ".github/workflows/back_deploy.yml"

jobs:
  # Build and test job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          cd AI
          uv sync

      - name: Setup test environment
        run: |
          cd AI
          mkdir -p logs
          # Set required environment variables for testing
          echo "DEBUG=True" >> $GITHUB_ENV
          echo "DATABASE_TYPE=mongodb" >> $GITHUB_ENV
          echo "MONGODB_URL=mongodb://test:test@localhost:27017/test_db" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV


      - name: Run tests
        run: |
          cd AI
          uv run pytest -v

      - name: Build Docker image
        run: |
          cd AI
          docker build -t ai-microservice:latest .

      - name: Test Docker image
        run: |
          cd AI
          docker run --rm ai-microservice:latest python -c "import app; print('Backend build successful')"

  # Deploy job using CapRover CLI
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Create deployment tarball
        run: |
          cd AI
          tar -czf ../ai-microservice.tar.gz .

      - name: Deploy to CapRover
        run: |
          caprover deploy \
            --caproverUrl "${{ secrets.CAPROVER_URL }}" \
            --caproverPassword "${{ secrets.CAPROVER_PASSWORD }}" \
            --appName "${{ secrets.CAPROVER_APP_NAME }}" \
            --tarFile ./ai-microservice.tar.gz
